# Generated by Django 3.1.7 on 2021-02-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название компании', max_length=200)),
                ('manager', models.CharField(help_text='Контактное лицо', max_length=200)),
                ('description', models.TextField(help_text='Краткое описание компании', max_length=1000)),
                ('pub_date', models.DateField(blank=True, help_text='Дата записи', null=True)),
                ('change_date', models.DateField(blank=True, help_text='Дата изменения записи', null=True)),
                ('adress', models.CharField(help_text='Адрес доставки партии меда', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Электронная почта', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Phonenumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Номер телефона', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название сорта меда', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя поставщика', max_length=50)),
                ('last_name', models.CharField(help_text='Фамилия поставщика', max_length=50)),
                ('patronymic', models.CharField(help_text='Отчество поставщика', max_length=50)),
                ('amount_of_honey', models.IntegerField(help_text='Колчество меда в килограммах')),
                ('price', models.IntegerField(help_text='Цена за киллограмм')),
                ('status_of_analysis', models.CharField(blank=True, choices=[('n', 'Не взят'), ('y', 'Взяли'), ('c', 'Проверяется в лаборатории'), ('r', 'Готов, но результаты еще не пришли'), ('w', 'С антибиотиком'), ('b', 'Без антибиотика')], default='n', help_text='Статус готовности агализа', max_length=1)),
                ('date_of_export', models.DateField(blank=True, help_text='Дата вывоза меда', null=True)),
                ('phonenumber', models.ManyToManyField(help_text='Телефонные номера поставщика', to='orders.Phonenumbers')),
                ('sort', models.ForeignKey(help_text='Сорт меда у поставщика', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.sorts')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название заказа(например Заказ на 2000кг)', max_length=200)),
                ('date_of_start', models.DateField(blank=True, null=True)),
                ('date_of_end', models.DateField(blank=True, null=True)),
                ('short_description', models.TextField(help_text='Краткое описание заказа(например Компания оформила заказ, уже оплатила(не оплатила) и тому подобное))', max_length=3000)),
                ('amount_of_honey', models.IntegerField(help_text='Количество заказанного меда в килограммах')),
                ('price', models.IntegerField(help_text='Цена за килограмм')),
                ('company', models.ForeignKey(help_text='Компания, для которой выполняется заказ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.companies')),
                ('sort', models.ForeignKey(help_text='Сорт меда в заказе', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.sorts')),
                ('suppliers', models.ManyToManyField(blank=True, help_text='Поставщики задействованные в заказе', to='orders.Suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок сообщения', max_length=100)),
                ('description', models.TextField(help_text='Вид обращения, комментарий', max_length=1000)),
                ('mark', models.CharField(blank=True, choices=[('g', 'Хорошо'), ('b', 'Плохо')], default='g', help_text='Оценка связи с компанией', max_length=1)),
                ('manager', models.CharField(max_length=50)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
        migrations.AddField(
            model_name='companies',
            name='emails',
            field=models.ManyToManyField(help_text='Электронные адреса компании', to='orders.Emails'),
        ),
        migrations.AddField(
            model_name='companies',
            name='phonenumbers',
            field=models.ManyToManyField(help_text='Телефонные номера компании', to='orders.Phonenumbers'),
        ),
    ]
