# Generated by Django 3.1.7 on 2021-02-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name': 'Электронный адрес', 'verbose_name_plural': 'Электронные адреса'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='phonenumbers',
            options={'verbose_name': 'Номер телефона', 'verbose_name_plural': 'Номера телефона'},
        ),
        migrations.AlterModelOptions(
            name='sorts',
            options={'verbose_name': 'Сорт меда', 'verbose_name_plural': 'Сорта меда'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
