# Generated by Django 3.1.7 on 2021-02-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210222_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorts',
            name='name',
            field=models.CharField(help_text='Название сорта меда', max_length=50, verbose_name='Название сорта'),
        ),
    ]
