# Generated by Django 3.1.7 on 2021-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210222_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='adress',
            field=models.CharField(help_text='Адрес доставки партии меда', max_length=100, verbose_name='Адрес доставки партии меда'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='change_date',
            field=models.DateField(blank=True, help_text='Дата изменения записи', null=True, verbose_name='Дата изменения записи'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='description',
            field=models.TextField(help_text='Краткое описание компании', max_length=1000, verbose_name='Краткое описание компании'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='manager',
            field=models.CharField(help_text='Контактное лицо', max_length=200, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(help_text='Название компании', max_length=200, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='pub_date',
            field=models.DateField(blank=True, help_text='Дата записи', null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(help_text='Электронная почта', max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='description',
            field=models.TextField(help_text='Разговор по телефону с менеджером. Сказали, что денег больше не дадут', max_length=1000, verbose_name='Вид обращение, комментарий'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='manager',
            field=models.CharField(max_length=50, verbose_name='Имя менеджера'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='mark',
            field=models.CharField(blank=True, choices=[('g', 'Хорошо'), ('b', 'Плохо')], default='g', help_text='Оценка связи с компанией', max_length=1, verbose_name='Оценка обращения'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='title',
            field=models.CharField(help_text='Например: Разговор с менеджером компании', max_length=100, verbose_name='Заголовок сообщения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount_of_honey',
            field=models.IntegerField(help_text='В килограммах', verbose_name='Количество меда'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(help_text='Например: Заказ на 2000кг', max_length=200, verbose_name='Название заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(help_text='В гривнах', verbose_name='Цена за килограмм'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='short_description',
            field=models.TextField(help_text='Например: Компания оформила заказ, уже оплатила(не оплатила) и т.д.', max_length=3000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='number',
            field=models.CharField(help_text='Номер телефона', max_length=30, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='amount_of_honey',
            field=models.IntegerField(help_text='В килограммах', verbose_name='Количество меда'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='first_name',
            field=models.CharField(help_text='Имя', max_length=50, verbose_name='Имя поставщика'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='last_name',
            field=models.CharField(help_text='Фамилия', max_length=50, verbose_name='Фамилия поставщика'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='patronymic',
            field=models.CharField(help_text='Отчество', max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='price',
            field=models.IntegerField(help_text='В гривнах', verbose_name='Цена за килограмм'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='status_of_analysis',
            field=models.CharField(blank=True, choices=[('n', 'Не взят'), ('y', 'Взяли'), ('c', 'Проверяется в лаборатории'), ('r', 'Готов, но результаты еще не пришли'), ('w', 'С антибиотиком'), ('b', 'Без антибиотика')], default='n', help_text='Выбирете статус анализа', max_length=1, verbose_name='Статус Анализа'),
        ),
    ]
