# Generated by Django 3.1.7 on 2021-02-22 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210222_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='emails',
            field=models.ManyToManyField(help_text='Выберите электронные адреса поставщика', to='orders.Emails', verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='phonenumbers',
            field=models.ManyToManyField(help_text='Выберите номера телефонов компании', to='orders.Phonenumbers', verbose_name='Номера телефонов'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='company',
            field=models.ForeignKey(help_text='Компания, для которой выполняется заказ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.companies', verbose_name='Выберите компанию'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_of_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания выполнения заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_of_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала выполнения заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sort',
            field=models.ForeignKey(help_text='Сорт', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.sorts', verbose_name='Сорт меда'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='suppliers',
            field=models.ManyToManyField(blank=True, help_text='Выберите поставщиков', to='orders.Suppliers', verbose_name='Поставщики'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phonenumber',
            field=models.ManyToManyField(help_text='Выберите номер телефона поставщика', to='orders.Phonenumbers', verbose_name='Номера телефона поставщика'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='sort',
            field=models.ForeignKey(help_text='Выберите сорт меда', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.sorts', verbose_name='Сорт меда'),
        ),
    ]
