# Generated by Django 3.1.7 on 2021-02-25 19:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20210222_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 21, 6, 9, 373013), verbose_name='Дата публикации сообщения'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
