# Generated by Django 3.1.7 on 2021-02-25 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210225_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 21, 8, 35, 717672), verbose_name='Дата публикации сообщения'),
        ),
    ]
