# Generated by Django 3.1.7 on 2021-02-26 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210225_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'permissions': (('can_edit', 'Edit message'),), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='companies',
            name='change_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 26, 21, 46, 34, 616845), help_text='Дата изменения записи', null=True, verbose_name='Дата изменения записи'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 26, 21, 46, 34, 616845), help_text='Дата записи', null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 21, 46, 34, 626723), verbose_name='Дата публикации сообщения'),
        ),
    ]
