# Generated by Django 3.1.7 on 2021-02-26 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210226_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'permissions': (('can_view_list_of_companies', 'Can view list of companies'),), 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterField(
            model_name='companies',
            name='change_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 26, 21, 56, 13, 116641), help_text='Дата изменения записи', null=True, verbose_name='Дата изменения записи'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 26, 21, 56, 13, 116641), help_text='Дата записи', null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 21, 56, 13, 116641), verbose_name='Дата публикации сообщения'),
        ),
    ]
