# Generated by Django 3.1.7 on 2021-02-26 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210226_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'permissions': (('can_view_list_of_messages', 'Can view list of messages'),), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'permissions': (('can_view_list_of_orders', 'Can view list of orders'),), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'permissions': (('can_view_list_of_suppliers', 'Can view list of suppliers'),), 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='companies',
            name='change_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 26, 22, 5, 28, 515843), help_text='Дата изменения записи', null=True, verbose_name='Дата изменения записи'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 26, 22, 5, 28, 515843), help_text='Дата записи', null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 22, 5, 28, 520850), verbose_name='Дата публикации сообщения'),
        ),
    ]
