# Generated by Django 3.1.7 on 2021-02-27 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210226_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'permissions': (('can_view', 'Can view'),), 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'permissions': (('can_view', 'Can view'),), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'permissions': (('can_view', 'Can view'),), 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='companies',
            name='change_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 27, 10, 26, 21, 876771), help_text='Дата изменения записи', null=True, verbose_name='Дата изменения записи'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 27, 10, 26, 21, 876771), help_text='Дата записи', null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 10, 26, 21, 880749), verbose_name='Дата публикации сообщения'),
        ),
    ]
