# Generated by Django 3.1.7 on 2021-02-27 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210227_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='change_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 27, 10, 30, 5, 750146), help_text='Дата изменения записи', null=True, verbose_name='Дата изменения записи'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 27, 10, 30, 5, 750146), help_text='Дата записи', null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 10, 30, 5, 754137), verbose_name='Дата публикации сообщения'),
        ),
    ]
