# Generated by Django 3.1.7 on 2021-02-27 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210227_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'permissions': (('can_view_list_of_companies', 'Can view list of companies'),), 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'permissions': (('can_view_list_of_messages', 'Can view list of messages'),), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'permissions': (('can_view_list_of_suppliers', 'Can view list of suppliers'),), 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='companies',
            name='change_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 27, 10, 57, 14, 83815), help_text='Дата изменения записи', null=True, verbose_name='Дата изменения записи'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 27, 10, 57, 14, 83815), help_text='Дата записи', null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 10, 57, 14, 87804), verbose_name='Дата публикации сообщения'),
        ),
    ]
