# Generated by Django 3.1.7 on 2021-02-28 09:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0014_auto_20210228_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='change_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 28, 11, 14, 11, 393839), help_text='Дата изменения записи', null=True, verbose_name='Дата изменения записи'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 28, 11, 14, 11, 393839), help_text='Дата записи', null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 11, 14, 11, 393839), verbose_name='Дата публикации сообщения'),
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Задание для персонала', max_length=250, verbose_name='Название задания')),
                ('task', models.TextField(max_length=3000, verbose_name='Задание')),
                ('pub_date', models.DateField(default=datetime.datetime(2021, 2, 28, 11, 14, 11, 393839), verbose_name='Дата выдачи задания')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания задания')),
                ('done', models.CharField(blank=True, choices=[('d', 'Выполнено'), ('n', 'Не выполнено')], default='n', help_text='Задание выполнено или нет', max_length=1, verbose_name='Выполнение')),
                ('excutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задание для персонала',
                'verbose_name_plural': 'Задания для персонала',
                'permissions': (('can_set_as_done', 'Can set as done'),),
            },
        ),
    ]
