# Generated by Django 3.1.7 on 2021-02-28 09:26

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0015_auto_20210228_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='excutor',
        ),
        migrations.AddField(
            model_name='todolist',
            name='excutors',
            field=models.ManyToManyField(help_text='Выберите исполнителей', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='change_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 28, 11, 26, 47, 650902), help_text='Дата изменения записи', null=True, verbose_name='Дата изменения записи'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 28, 11, 26, 47, 650902), help_text='Дата записи', null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 11, 26, 47, 650902), verbose_name='Дата публикации сообщения'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 28, 11, 26, 47, 650902), verbose_name='Дата выдачи задания'),
        ),
    ]
