# Generated by Django 3.1.7 on 2021-02-28 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210228_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='change_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 28, 9, 30, 24, 24156, tzinfo=utc), help_text='Дата изменения записи', null=True, verbose_name='Дата изменения записи'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 28, 9, 30, 24, 24156, tzinfo=utc), help_text='Дата записи', null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 11, 30, 24, 24156), verbose_name='Дата публикации сообщения'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 28, 9, 30, 24, 24156, tzinfo=utc), null=True, verbose_name='Дата выдачи задания'),
        ),
    ]
