# Generated by Django 3.1.7 on 2021-02-28 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20210228_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 11, 44, 5, 46646), verbose_name='Дата публикации сообщения'),
        ),
    ]
