# Generated by Django 3.1.7 on 2021-02-28 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20210228_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'permissions': (('can_set_as_done', 'Can set as done'), ('can_view_my_tasks', 'Can view my tasks')), 'verbose_name': 'Задание для персонала', 'verbose_name_plural': 'Задания для персонала'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 11, 47, 29, 255902), verbose_name='Дата публикации сообщения'),
        ),
    ]
