# Generated by Django 3.1.7 on 2021-02-28 09:59

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0021_auto_20210228_1147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='Tasks',
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 11, 58, 53, 319519), verbose_name='Дата публикации сообщения'),
        ),
    ]
