# Generated by Django 3.1.7 on 2021-03-01 12:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20210228_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonenumbersComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Номер телефона', max_length=30, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефона',
            },
        ),
        migrations.CreateModel(
            name='PhonenumbersSupp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Номер телефона', max_length=30, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефона',
            },
        ),
        migrations.RemoveField(
            model_name='companies',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='phonenumbers',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='emails',
            name='company',
            field=models.ForeignKey(help_text='Электронный адрес компании', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.companies', verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 14, 17, 49, 314867), verbose_name='Дата публикации сообщения'),
        ),
        migrations.DeleteModel(
            name='Phonenumbers',
        ),
        migrations.AddField(
            model_name='phonenumberssupp',
            name='supplier',
            field=models.ForeignKey(help_text='Номер телефона Поставщика', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.suppliers', verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='phonenumberscomp',
            name='company',
            field=models.ForeignKey(help_text='Номер телефона компании', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.companies', verbose_name='Номер телефона'),
        ),
    ]
