# Generated by Django 3.1.7 on 2021-03-01 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20210301_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumberscomp',
            options={'verbose_name': 'Номер телефона компании', 'verbose_name_plural': 'Номера телефона компаний'},
        ),
        migrations.AlterModelOptions(
            name='phonenumberssupp',
            options={'verbose_name': 'Номер телефона поставщика', 'verbose_name_plural': 'Номера телефона поставщиков'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 14, 21, 34, 952689), verbose_name='Дата публикации сообщения'),
        ),
    ]
