# Generated by Django 3.1.7 on 2021-03-01 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20210301_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 14, 54, 12, 334554, tzinfo=utc), verbose_name='Дата публикации сообщения'),
        ),
    ]
