# Generated by Django 3.1.7 on 2021-03-02 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20210301_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер пользователя'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 8, 55, 31, 197765, tzinfo=utc), verbose_name='Дата публикации сообщения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d', verbose_name='Фото профиля'),
        ),
    ]
