# Generated by Django 3.1.7 on 2021-03-02 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20210302_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='done',
            field=models.CharField(blank=True, choices=[('d', 'Выполнено'), ('n', 'Не выполнено')], default='n', help_text='Задание выполнено или нет', max_length=1, verbose_name='Выполнение'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 9, 31, 50, 274589, tzinfo=utc), verbose_name='Дата публикации сообщения'),
        ),
    ]
