# Generated by Django 3.1.7 on 2021-03-02 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20210302_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 11, 2, 14, 672714, tzinfo=utc), verbose_name='Дата публикации сообщения'),
        ),
    ]
