# Generated by Django 3.1.7 on 2021-03-02 11:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20210302_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='company',
            field=models.ForeignKey(help_text='Электронный адрес компании', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.companies', verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 11, 33, 44, 690294, tzinfo=utc), verbose_name='Дата публикации сообщения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='company',
            field=models.ForeignKey(help_text='Компания, для которой выполняется заказ', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.companies', verbose_name='Выберите компанию'),
        ),
        migrations.AlterField(
            model_name='phonenumberscomp',
            name='company',
            field=models.ForeignKey(help_text='Номер телефона компании', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.companies', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='phonenumberssupp',
            name='supplier',
            field=models.ForeignKey(help_text='Номер телефона Поставщика', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.suppliers', verbose_name='Номер телефона'),
        ),
    ]
