# Generated by Django 3.1.7 on 2021-03-02 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20210302_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 12, 30, 4, 750867, tzinfo=utc), verbose_name='Дата публикации сообщения'),
        ),
    ]
