# Generated by Django 3.1.7 on 2021-03-04 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20210302_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 10, 43, 44, 473249, tzinfo=utc), verbose_name='Дата публикации сообщения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sort',
            field=models.CharField(blank=True, help_text='Сорт', max_length=200, null=True, verbose_name='Название сорта меда'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='sort',
            field=models.CharField(blank=True, help_text='Сорт', max_length=200, null=True, verbose_name='Название сорта меда'),
        ),
    ]
