# Generated by Django 3.1.7 on 2021-03-04 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20210304_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='amount_of_honey',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='amount_of_honey',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='messages',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации сообщения'),
        ),
    ]
