# Generated by Django 3.1.7 on 2021-03-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20210304_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='channel',
            field=models.CharField(blank=True, choices=[('z', 'Заявка'), ('l', 'Письмо'), ('s', 'Сайт'), ('i', 'Инициатива компании'), ('p', 'Звонок')], default='', max_length=1, verbose_name='Канал обращения'),
        ),
    ]
