# Generated by Django 3.1.7 on 2021-03-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_messages_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'ordering': ['-name'], 'permissions': (('can_view_list_of_companies', 'Can view list of companies'),), 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='description',
            field=models.TextField(help_text='Например: Разговор по телефону с менеджером. Сказали, что денег больше не дадут.', max_length=1000, verbose_name='Вид обращение, комментарий'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='title',
            field=models.CharField(help_text='Например: Разговор с менеджером компании.', max_length=100, verbose_name='Заголовок сообщения'),
        ),
    ]
