from django.urls import path
from . import views
from django.conf.urls import url
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^companies/$', views.CompaniesListView.as_view(), name='companies'),
    url(r'^searchcomp/$', views.Searchcomp.as_view(), name='searchcomp'),
    url(r'^company/(?P<pk>\d+)$', views.CompanyDetailView.as_view(), name='company-detail'),
    url(r'^suppliers/$', views.SuppliersListView.as_view(), name='suppliers'),
    url(r'^searchsupp/$', views.Searchsupp.as_view(), name='searchsupp'),
    url(r'^supplier/(?P<pk>\d+)$', views.SuppliersDetailView.as_view(), name='suppliers-detail'),
    url(r'^orders/$', views.OrdersListView.as_view(), name='orders'),
    url(r'^order/(?P<pk>\d+)$', views.OrdersDetailView.as_view(), name='orders-detail'),
    url(r'^messages/$', views.MessagesListView.as_view(), name='messages'),
    url(r'^messages/(?P<pk>\d+)$', views.MessagesDetailView.as_view(), name='messages-detail'),
    url(r'^mymessages/$', views.AllMessagesByUserListView.as_view(), name='my-messages'),
    url(r'^tasks/$', views.TasksListView.as_view(), name='tasks'),
    url(r'^task/(?P<pk>\d+)$', views.TaskDetailView.as_view(), name='task-detail'),
    url(r'^searchtask/$', views.Searchtask.as_view(), name='searchtask'),
    url(r'^mytasks/$', views.MyTaskListView.as_view(), name='my-tasks'),
    url(r'^mytask/(?P<pk>\d+)/update/$', views.SetTaskAsDone.as_view(), name='task_update_by_worker'),
    url(r'^orderdone/(?P<pk>\d+)/update/$', views.SetOrderAsDone.as_view(), name='order_done'),
    url(r'^company/create/$', views.CompanyCreate.as_view(), name='company_create'),
    url(r'^company/(?P<pk>\d+)/update/$', views.CompanyUpdate.as_view(), name='company_update'),
    url(r'^company/(?P<pk>\d+)/delete/$', views.CompanyDelete.as_view(), name='company_delete'),
    url(r'^order/create/$', views.OrderCreate.as_view(), name='order_create'),
    url(r'^order/(?P<pk>\d+)/update/$', views.OrderUpdate.as_view(), name='order_update'),
    url(r'^order/(?P<pk>\d+)/delete/$', views.OrderDelete.as_view(), name='order_delete'),
    url(r'^task/create/$', views.TaskCreate.as_view(), name='task_create'),
    url(r'^task/(?P<pk>\d+)/update/$', views.TaskUpdate.as_view(), name='task_update'),
    url(r'^task/(?P<pk>\d+)/delete/$', views.TaskDelete.as_view(), name='task_delete'),
    url(r'^messages/create/$', views.MessageCreate.as_view(), name='message_create'),
    url(r'^messages/(?P<pk>\d+)/update/$', views.MessageUpdate.as_view(), name='message_update'),
    url(r'^messages/(?P<pk>\d+)/delete/$', views.MessageDelete.as_view(), name='message_delete'),
    url(r'^supplier/create/$', views.SupplierCreate.as_view(), name='supplier_create'),
    url(r'^supplier/(?P<pk>\d+)/update/$', views.SupplierUpdate.as_view(), name='supplier_update'),
    url(r'^supplier/(?P<pk>\d+)/delete/$', views.SupplierDelete.as_view(), name='supplier_delete'),
    url(r'^profile/(?P<pk>\d+)$', views.ProfileDetailView.as_view(), name='profile'),
    url(r'^edit/', views.edit, name='edit-profile'),
    url(r'filter/', views.FilterOrdersListView.as_view(), name='filter'),
    url(r'filtermessages/', views.FilterMessagesListView.as_view(), name='filtermessages'),
]